### ISSUE TITLE
Show list of transactions on the block details screen

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#100]
Currently there is no way to see the list of transactions which belong to a specific block.
Ideally, they should show up on the block details screen (`/blocks/${blockId}`)

**Comment by jondubois** [comment]
Or there could be a separate details screen for blocks. Similar to the accounts transactions details screen. Just as there is a'VIEW TRANSACTIONS' button on the account screen, there could be a `VIEW TRANSACTIONS` button on the blocks screen.

**Comment by maarteNNNN** [comment]
Merged in https://github.com/Capitalisk/ldpos-wallet/pull/101.
