### ISSUE TITLE
Delegate vote weight and forging rewards should show result in token units

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#102]
Currently, delegate `voteWeight` and `forgingRewards` are displayed in the smallest possible units.
They should be displayed in token units (e.g. CLSK).

Note that the `forgingRewards` property was recently added so some nodes may not have it (will be `undefined`) so the application should not break if this happens.

**Comment by maarteNNNN** [comment]
![image](https://user-images.githubusercontent.com/14275291/166951971-a4f8eb4d-410f-4bb6-8f3c-f4249c639f2f.png)

Seems like it's already correct?

**Comment by jondubois** [comment]
Ah yep I implemented it already.
