### ISSUE TITLE
After signing into a different blockchain than CLSK, it always says that wallet address is invalid

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#24]
After switching to `foo` testnet blockchain (networkSymbol: `foo`, moduleName: `foo_chain`), when I try to send some tokens to another address starting with `foo...` (instead of `clsk...`), it always says that the address is invalid (it still expects address to start with `clsk` even though it should start with `foo`).

**Comment by maarteNNNN** [comment]
This should be fixed during the rework of the blockchain switcher
