### ISSUE TITLE
Make the distinction between Wallet and Transactions more clear

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#3]
Right now the difference between `Wallet` screen and `Transactions` screen is not obvious.

Possible solutions:

- Rename `Transactions` to `All transactions` (also rename with `Blocks` to `All blocks` and `Accounts` to `All accounts`)
- Change the heading on the screen itself to `All transactions`

Or find another way to make the distinction a bit more clear.

**Comment by maarteNNNN** [comment]
Fixed in b52e0b63d505ee62d45bb176422cefb2781af8d6

**Comment by maarteNNNN** [comment]
I renamed the titles but left the sidebar as is. I think users will get comfortable the way it is. One sweep in the app and they'll understand what is what. `All transactions`, `All blocks` and `All accounts` looks off in the sidebar
