### ISSUE TITLE
Manage networks screen

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#37]
There should be a screen to allow the user to manage networks (needs to work on both desktop and web; it can edit the `config.json` file on desktop and use localStorage for web). The user should be able to add new networks based on custom `IP/hostname`, `port`, `moduleName`, `networkSymbol` and also there should be a property called `protocol` which should default to `auto` but other options should be `wss` and `ws`.

`protocol: auto` should be the current behaviour (it appears to work this way right now; I think it may be inside `socketcluster-client` when the protocol is not specified): If the page is served over HTTPS, it will use `wss` otherwise if using HTTP, it will be `ws`.

This feature should work for both desktop and web.

**Comment by maarteNNNN** [comment]
see #53 for additional requested changes
