### ISSUE TITLE
Do not show network in the network switcher if it is not available for the current environment (I.e. mainnet or testnet)

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#43]
When running the app in mainnet mode, I can see networks like `foo` which are only testnet. When I click on it in the network switcher, it shows an error.

**Comment by maarteNNNN** [comment]
I let the production version only choose `mainnet`, I made a commit that filters only for the mainnet values. I'll add a setting to force to show the type select. 8f458f9ca668c9892c86f29de264f15d2cd10ded
