### ISSUE TITLE
Delegates page only shows forging delegates instead of all delegates

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#46]
Currently, the `Delegates` page only shows delegates which have non-zero `voteWeight`. It should use the `ldposClient.getDelegatesByVoteWeight(offset, limit, 'desc')` instead of `ldposClient.getForgingDelegates()`.

**Comment by jondubois** [comment]
Also this should be done for the `Voting` page as well.

**Comment by maarteNNNN** [comment]
@jondubois I think this is related to the function of the `ldpos-client` it's using: `getDelegatesByVoteWeight`
