### ISSUE TITLE
Delegate search is broken

### ISSUE THREAD

**Issue by maarteNNNN** [Capitalisk/ldpos-wallet#47]
- Searching for a specific delegate to see how much voteWeight they have - It can help guide people's voting decisions (for example if the delegate is almost in the top 15)
- Seeing how many tokens a specific account has (along with other account details)
- Seeing a list of transactions which were recently sent to/from a specific account (I often use this feature in Lisk Explorer to check if I've already paid someone).

**Comment by jondubois** [comment]
The last two have been implemented but the delegate search by address feature is broken.

**Comment by jondubois** [comment]
Fixed.
