### ISSUE TITLE
Wallet shows horizontal scrollbar

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#5]
- Some columns should be removed. The `message` can be very big (up to 256 characters) so it shouldn't be shown on this screen. Instead, the user should be able to click on the transaction to see more details.
- Not sure why two columns show wallet addresses. There should be one wallet address column at most (the `recipientAddress` for transfer transactions).

**Comment by maarteNNNN** [comment]
I tried reducing it as much as possible on a desktop with wrapping the words depending on the size and if scroll is enforced. This only gets fired actually on load. So when resizing this doesn't fire. It would reduce performance re-rendering the component too much.
