### ISSUE TITLE
Incorrect URLs for accounts section

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#61]
When clicking on any account in the table on the `Accounts` screen, the URL is in the form `https://capitalisk.com/wallet/ldpos/#/wallet/clskdef790ebcd2651a85deaeae1945e336cff30ca06`

If you try to copy and paste this URL directly in the browser (in a different tab), it doesn't work. It seems that the correct URL should have been: `https://capitalisk.com/wallet/ldpos/#/accounts/clskdef790ebcd2651a85deaeae1945e336cff30ca06`

**Comment by maarteNNNN** [comment]
I tried reproducing this error. However for me it's generating the link correctly. @jondubois What's the browser version you tested it in?

**Comment by jondubois** [comment]
@maarteNNNN I made the fix already but forgot to close this. You can check it here https://github.com/Capitalisk/ldpos-wallet/commit/0b871c84c17e053e3f0aaed4ecacd384d445e9d7
