### ISSUE TITLE
Data should become updated

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#65]
Currently there is no way to get the latest updated data. If a transaction was processed recently, we have to navigate away from the screen and then come back to the screen in order to see the new transaction.

There should either be a refresh button to allow the user to fetch the latest data or it should be updated automatically in real time.

**Comment by sacOO7** [comment]
I think we can just fetch latest transactions every 10 seconds, passing
last transaction id. That probably should just work fine.

**Comment by maarteNNNN** [comment]
I think 10 seconds will be annoying, if everyone leaves the wallet open for long periods of time we're polling for nothing. I'm going to do do it however but do a `window.addEventListener('blur')` to clear the poll and `window.addEventListener('focus')` to activate the poll to reduce calls. On focus the call is done directly.

See commit b39aad8957f253b178c32177fbcd83dc2c7b5445
