### ISSUE TITLE
After logging me out automatically, it doesn't let me view the transactions screen

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#66]
After the wallet logged me out automatically after timeout, it does not allow me to view the transactions screen - It keeps redirecting me to the wallet screen.

Also, it would be better if the wallet did not log me out so quickly (or at all). It's OK to stay logged in for a whole day. It's the user's responsibility to click on the logout button or to close the app.

**Comment by maarteNNNN** [comment]
@jondubois It should work though. I couldn't reproduce this error. 

See
https://github.com/Capitalisk/ldpos-wallet/blob/4e3fa5b0ef52e62ebde83a9ac57e538cf63eb32e/src/store/index.js#L105-L134

Anyway I commented the interval function in e2d74b948280fd82d18315e08fbc5612fe27ff25

**Comment by maarteNNNN** [comment]
@jondubois it would be good to have a function to deauthenticate rather than `disconnect` and `connect` again.
