### ISSUE TITLE
Improve UI on mobile

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#80]
Right now, when viewed on a mobile device, there are both horizontal scroll bars on most pages.
This is unwieldy and users can lose track if they scroll too far right.

We should aim for a design which only has vertical scrolling. This will likely mean that some table columns will need to be hidden on mobile. On mobile, we should show as little data as necessary in the tables; if a user wants to see more details about a transaction or account, they can click on it.

**Comment by maarteNNNN** [comment]
@jondubois https://github.com/Capitalisk/ldpos-wallet/issues/14 should take care of that. What the ideal case would be is that the user selects their wanted information and the table adjusts it to the users wishes.

The groundwork has been done for this. However it's far from being able to implement yet.

Although I think that we can't make it so the horizontal scroll becomes less abundant on mobile. We need much information and we have few space to represent them. I ultimately think that a table isn't to bad to have horizontal scrolling. We could however improve it with the pagination PR(#78), to make it so vertical scrolling becomes absolute. And make sure the pagination stays centered whatever the case on mobile. It will be more intuitive for the user.

**Comment by maarteNNNN** [comment]
@jondubois already improved this.
