### ISSUE TITLE
Handle error in `DetailedData.vue`

### ISSUE THREAD

**Issue by maarteNNNN** [Capitalisk/ldpos-wallet#81]
Error is of type Object and we want to display it accurately, maybe even in red.

```json
{
  "name": "VoterAlreadyVotedForDelegateError",
  "message": "Voter clskbc84c66b69477c2160ef2eb5c92579840fa0ef3f has already voted for delegate clskbde48efe4fb34f91f3bfad4e4e8feb081b302b0f"
}
```

See [this transaction](http://localhost:8080/#/transactions/e5af4645037dcad2f73298cc2e9683d85f511a23) on the testnet where I encountered the problem.

**Comment by jondubois** [comment]
I just added this today on the backend. I was thinking that it would be good to show a red cross next to these transactions (those which have an `error`) in the table view so that the user can quickly see if their last transaction failed.

**Comment by maarteNNNN** [comment]
See 7cad67ac8bbe3236c385256c0565b9ee2e006159

![image](https://user-images.githubusercontent.com/14275291/189547665-add924e3-5338-4663-aa76-e41a57e63ac5.png)
