### ISSUE TITLE
Raise confirmation popup before hard refresh

### ISSUE THREAD

**Issue by sacOO7** [Capitalisk/ldpos-wallet#85]
Current behavior - when clicked on browser refresh, the session automatically logs out
Expected - it should ask for confirmation mentioning if want to continue with hard refresh with proper warning. 

- We have same mechanism in ldex.trading

**Comment by maarteNNNN** [comment]
I particularly don't like this. Especially not without any pending interaction with the chain. TBH I hate having to click a confirmation on the LDEX platform. I don't know why if I click on close it prohibits my instruction. Not very user friendly IMO.
