### ISSUE TITLE
Pagination extra's

### ISSUE THREAD

**Issue by maarteNNNN** [Capitalisk/ldpos-wallet#89]
Some additional improvements which are going to be an enhancement of pr #78 
- [ ] Add first page
- [ ] Add input to go to a specified page
- [ ] ~~Add last page~~ (unable due to api limitations)
- [ ] Tests
- [ ] Polling isn't clearing correctly
- [ ] Verify that polling is only done on page 1

**Comment by jondubois** [comment]
Unfortunately, we cannot know how many elements or how many pages there are in total for any specific endpoint. It would be too expensive to compute the number of records on the backend. Google search results also don't tell you the number of pages and only give you an estimate about the number of results (probably for the same reason).

**Comment by jondubois** [comment]
@maarteNNNN There seems to be an issue with pagination of transaction page. When I go forward several page, then I go back again to page 1, the first record is no longer the latest transaction. The first page should always show the latest transaction.
