### ISSUE TITLE
Pagination order issue on blocks screen

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#9]
The height counts down correctly on the first page of records but once more records are loaded, the height skips and starts counting up.

In the `getBlocksByTimestamp`, the order is `asc`; it should be `desc`:  `{offset: 25, limit: 25, order: "asc"}`

**Comment by maarteNNNN** [comment]
this is fixed, however I opened #18 for some additional improvements on sorting
