### ISSUE TITLE
The ranks on the accounts page is incorrect when you go to the second page and later

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldpos-wallet#91]
https://capitalisk.com/wallet/ldpos/#/accounts

The top account on any page always shows rank as `#1` and second row as `#2`, etc...

**Comment by maarteNNNN** [comment]
Seems to be related to the pagination now. When switching pages back and forth @jondubois.
![image](https://user-images.githubusercontent.com/14275291/144442469-175d9743-fce3-4354-bcd7-2302b8480c66.png)

Although this is being calculated on the front-end I think it would be better to include this on the backend, WDYT?

**Comment by jondubois** [comment]
Maybe we can remove the rank?

**Comment by maarteNNNN** [comment]
> Maybe we can remove the rank? Or you can calculate based on the current page number.
The rank is not tracked on the backend.

This skipped passed me, I think it's interesting to see the rank so that you can know if you're within the required delegate position.

**Comment by jondubois** [comment]
Ranks were removed for now.

**Comment by maarteNNNN** [comment]
@jondubois Is this solved?

**Comment by jondubois** [comment]
It's done.
